# Generated by Django 5.2.6 on 2026-08-30 17:21

import django.utils.timezone
from django.db import migrations, models


def populate_sale_datetimes(apps, schema_editor):
    Sale = apps.get_model('Grocery', 'Sale')
    for sale in Sale.objects.all():
        if sale.date_sold:
            sale.sale_datetime = sale.date_sold
            sale.created_at = sale.date_sold
            sale.save(update_fields=['sale_datetime', 'created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0002_alter_product_min_stock_level_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.RunPython(populate_sale_datetimes, migrations.RunPython.noop),
    ]
